import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/quiz.module.css'

export default function Quiz() {
    return (
      <>
        <Head>
          <title>Under the Waves | Quiz</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Image
            className={styles.iphonesize}
            src={"/public/wide_box.png"}
            width={410}
            height={945}
          />
        </main>
      </>
    )
  }