import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/about.module.css'
import Topnavbar from '@/components/top-navbar'
import Navbar from '@/components/navbar'
import Link from 'next/link'

export default function About() {

  return (
    <>
      <Head>
        <title>Under the Waves | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Pixel/utwalogo.png" />
      </Head>
      <main className={styles.main}>
        <audio autoPlay src={"/music/Bubbline.mp3"} loop="true" autostart="true"></audio>
        <div className={styles.navBar}>
          <Topnavbar/>
        </div>
        <h1 id={"about"} className={styles.pageTitle}>About</h1>
          <div className={styles.content_1}>
            <div>
              <h2 className={styles.whiteText}>Under the Waves</h2>
              <p className={styles.aboutDescription}>
                Under The Waves is an
                <span className={styles.pinkText}> adventure + learning</span> game where you explore the ocean while learning about the sea creatures and the current issues they are facing today.
              </p>
            </div>
            <div className={styles.separator}>
              <Image
                src={"/animals/seahorse.png"}
                width={40}
                height={40}
                />
              <Image
                src={"/animals/seahorse.png"}
                width={40}
                height={40}
                />
              <Image
                src={"/animals/seahorse.png"}
                width={40}
                height={40}
                />
            </div>

          </div>
        <div className={styles.content_2}>
          <h2 id={"icons"} className={styles.whiteText}>Icons</h2>
          <div className={styles.section}>
            <h2 id={"home"}>Home</h2>
            <Image src={"/icons/home.svg"} width={50} height={50}></Image>
            <p>This home icon leads you to the starting page where you can begin your journey learning and exploring.</p>
          </div>
          <div className={styles.section}>
            <h2>Beach</h2>
            <Image src={"/icons/beach.svg"} width={50} height={50}></Image>
            <p>
              In the beach you can interact with a variety of fishes and learn more about their behaviour, diets, habitats and many more.
            </p>
          </div>
          <div className={styles.section}>
            <h2>Aquarium</h2>
            <Image src={"/icons/aquarium.svg"} width={50} height={50}></Image>
            <p>
              The fish icon leads you to an aquarium Where you can place injured creatures that you rescued into it. You can take care of the fishes until they finally recover and return back to the ocean.
            </p>
          </div>
          <div className={styles.section}>
            <h2>Market</h2>
            <Image src={"/icons/market.svg"} width={50} height={50}></Image>
            <p>This market icon leads you to the shop where you can purchase items for your aquarium and your fishes.</p>
          </div>
          <div className={styles.section}>
            <h2>Quiz</h2>
            <Image src={"/icons/quiz.svg"} width={50} height={50}></Image>
            <p>
              Lastly theres a quiz section where you can put your ocean knowledge to the test, you can also earn seashells to purchase items for your aquarium to give your fishes a happy home.
            </p>
          </div>
          <div className={styles.section}>
            <h2>Menu</h2>
            <Image src={"/icons/menu.svg"} width={50} height={50}></Image>
            <p>This icon is the menu, in here you can access the save, settings and quit buttons</p>
          </div>
        </div>
        <div id={"learn"}>

        </div>
      <Navbar></Navbar>
      </main>
    </>
  )
}