import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/aquarium.module.css'

export default function Aquarium() {
    return (
      <>
        <Head>
          <title>Under the Waves</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Image
            className={styles.iphonesize}
            src={"/iphoneMockUp.png"}
            width={410}
            height={831}
          />
        </main>
      </>
    )
  }