import Head from "next/head";
import Image from "next/image";
import Topnavbar from "@/components/top-navbar";
import Navbar from "@/components/navbar";
import Link from "next/link";
import BarChart from "@/components/BarChart";
import { Bar } from "react-chartjs-2";
import styles from '@/styles/settings.module.css'
import BarChart2 from "@/components/BarChart2";
import { useRouter } from "next/router";





export default function Graph() {
    const router = useRouter("")
   
    return (
        <>
        <Head>
        <title>Under the Waves | Info Section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Pixel/utwalogo.png" />
      </Head>
      <main>
        <Topnavbar title={"Facts"} />
        <Image onClick={() => router.back()}
          className={styles.backButton}
          src={"/buttons/settingsBack.svg"}
          alt={"/buttons/settingsBack.svg"}
          width={42}
          height={42}
        />
        <BarChart/>
        <BarChart2/>
        <Navbar/>
      </main>
        </>
    )
}