import Head from "next/head";
import Image from "next/image";
import Topnavbar from "@/components/top-navbar";
import Navbar from "@/components/navbar";
import Link from "next/link";
import BarChart from "@/components/BarChart";
import { Bar } from "react-chartjs-2";
import styles from '@/styles/settings.module.css'
import BarChart2 from "@/components/BarChart2";





export default function Graph() {
   
    return (
        <>
        <Head>
        <title>Under the Waves | Info Section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topnavbar title={"Facts"} />
        <BarChart/>
        <BarChart2/>
        <Navbar/>
      </main>
        </>
    )
}