import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Under the Waves</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image className={styles.mainImage} src={"/Pixel/Background/seaBackground.gif"}
          width={414}
          height={820}
        />
        <div className={styles.mainContent}>
          <h1 id={styles.mainTitle}>Under The Waves</h1>
          <div>
            <Image className={styles.character} src={"/Pixel/charac-higher-res.gif"} width={150} height={150}/>

            <p className={styles.mainDescription}>
              Welcome aboard, adventurer! Get ready to dive into a world of discovery and exploration as we embark on an exciting journey to the depths of the ocean.
            </p>
          </div>
          <div className={styles.navigationContainer}>
            <Link href={"/loadingpg"}>
              <Image className={styles.landingPgButtons}src={"/Pixel/startButton.svg"} height={49} width={186}alt='start button'/>
            </Link>
            <Link href={"/tutorial"}>
              <Image itemType='button' className={styles.landingPgButtons} src={"/Pixel/tutorialButton.svg"} height={49} width={186}alt='tutorial button'/>
            </Link>
          </div>
        </div>
      </main>    
    </>
  )
}
