import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import PopUp from '@/components/menu Popup'

export default function Home() {
  return (
    <>
      <Head>
        <title>Under the Waves</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PopUp/>
      <main className={styles.main}>
        <h1 id={styles.mainTitle}>Under The Waves.</h1>
        <p className={styles.mainDescription}>
          Welcome aboard, adventurer! Get ready to dive into a world of discovery and exploration as we embark on an exciting journey to the depths of the ocean.
        </p>

        <div className={styles.navigationContainer}>
          <Link href={"/beach"}>
            <Image className={styles.landingPgButtons}src={"/Pixel/startButton.svg"} height={100} width={155}alt='start button'></Image>
          </Link>
          <Link href={"/tutorial"}>
            <Image className={styles.landingPgButtons}src={"/Pixel/tutorialButton.svg"} height={100} width={155}alt='tutorial button'></Image>
          </Link>
          <Image src={"/Pixel/Background/seaBackground.gif"}
            width={500}
            height={1000}
          ></Image>
        </div>
      </main>    
    </>
  )
}
