import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/landingpg.module.css'
import Link from 'next/link'


export default function LoadingPage(){
    return(
        <>
            <Head>
                <title>Under the Waves</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.loadingBanner}>
                    <Image src={"/boxes/banner.png"} height={300} width={300}/>
                    <p className={styles.loadingTitle}>Are you ready to dive into the depths of the ocean and discover the fascinating creatures that call it home?</p>
                </div>
            </main>
        </>
    )
}