import Head from 'next/head'
import styles from "@/styles/quiz.module.css"
import Navbar from "@/components/navbar"
import Topnavbar from '@/components/top-navbar'
import Image from "next/image"
import { useState } from 'react'

export default function QuizPage(){

    const [showOceanQuiz, setOceanQuiz] = useState(false);
    const [showFishQuiz, setFishQuiz] = useState(false);

    function boopSound(){
        let audio = new Audio("/music/Bubble-boop.mp3");
        audio.play()
    }

    return(
        <>
            <Head>
            <title>Under the Waves | Quiz</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/Pixel/utwalogo.png" />
            </Head>
            <main className={styles.main}>
                <audio autoPlay src={"/music/Bubbling.mp3"} loop="true" autostart="true"></audio>
                <Topnavbar/>
                <h1 className={styles.headerTitle}>Quiz</h1>
                <div className={styles.container}>
                    <div className={styles.tips}>
                        <Image
                            className={styles.turtleFloat}
                            src={"/animals/green-turtle.png"}
                            width={120}
                            height={120}
                            alt='green turtle'
                        />
                        <p>
                            Are you ready to be quizzed about the ocean? <br></br>
                            Click on a topic to start the quiz!
                        </p>
                    </div>
                    <div className={styles.quizCategories}>
                        <div className={styles.quizSection}>
                            <Image 
                                className={styles.quizCover} 
                                src={"/animals/blue-whale.png"} 
                                width={50} 
                                height={50}
                                alt='blue whale'
                            />
                            <a className={styles.quizLink} href={"/oceanQuiz"}>
                                <p onClick={boopSound}>
                                    All about: <br></br>The Ocean
                                </p>
                            </a>
                        </div>
                        <div className={styles.quizSection} >
                            <Image 
                                className={styles.quizCover} 
                                src={"/animals/clown-fish.png"} 
                                width={50} 
                                height={50}
                                alt='clown fish'
                            />
                            <a className={styles.quizLink} href={"/fishQuiz"}>
                                <p onClick={boopSound}>
                                    All about: <br></br>Aquatic animals
                                </p>
                            </a>
                        </div>
                        <div className={styles.quizSection}>
                            <Image 
                                className={styles.quizCover} 
                                src={"/animals/octopus1.png"} 
                                width={50} 
                                height={50}
                                alt='octopus'
                            />
                            <a className={styles.quizLink} href={"/wasteQuiz"}>
                                <p onClick={boopSound}>
                                    All about: Environment
                                </p>
                            </a>
                        </div>
                    </div>
                </div>
                <Navbar/>
            </main>
        </>
    )
}