import Navbar from "@/components/navbar"
import Head from "next/head"
export default function Settings() {
    return (
      <>
        <Head>
          <title>Under the Waves | Settings</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1>Settings</h1>
          <img src='Pixel/Background/testbg4.svg'></img>
          <Navbar></Navbar>
        </main>
      </>
    )
  }