import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/shop.module.css'
import Navbar from '@/components/navbar'
import Topnavbar from '@/components/top-navbar'

export default function Shopitem() {
    return(
        <>
            <Head>
            <title>Under the Waves | Shop item_1</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Topnavbar/>
                <div>
                    
                </div>
                <Navbar/>
            </main>
        </>
    )
}