import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/tutorial.module.css'
import Topnavbar from '@/components/top-navbar'
import Navbar from '@/components/navbar'
import Link from 'next/link'

export default function Tutorial() {


  return (
    <>
      <Head>
        <title>Under the Waves | Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <audio autoPlay src={"/music/Bubbline.mp3"} loop="true" autostart="true"></audio>
        <div className={styles.navBar}>
          <Topnavbar/>
        </div>
        <div className={styles.tutorialNav}>
          <a href={"#about"}>About the game</a>
          <a href={"#icons"}>Icons</a>
          <a href={"#howto"}>How to play</a>
          <a href={"learn"}>Learn</a>
        </div>
        <h1 className={styles.pageTitle}>Tutorial</h1>
        <div className={styles.content_section}>
          <div className={styles.content_1}>
            <h2 id={"about"}>About</h2>
            <div id={"about"}>
              <p>
              Under The Waves is an <span>adventure + learning</span> game where you as a scuba diver explore the ocean while learning about the sea creatures.
            <div className={styles.separator}>
              <Image
                src={"/animals/seahorse.png"}
                width={40}
                height={40}
                />
              <Image
                src={"/animals/seahorse.png"}
                width={40}
                height={40}
                />
              <Image
                src={"/animals/seahorse.png"}
                width={40}
                height={40}
                />
            </div>
              </p>
            </div>
          </div>
        </div>
        <div className={styles.content_2}>
          <h2 id={"icons"}>Icons</h2>
          <div className={styles.section}>
            <h2 id={"home"}>Home</h2>
            <Image src={"/icons/home.svg"} width={50} height={50}></Image>
            <p>This home icon leads you to the starting page where you can being your journey learning and exploring.</p>
          </div>
          <div className={styles.section}>
            <h2>Beach</h2>
            <Image src={"/icons/beach.svg"} width={50} height={50}></Image>
            <p>
              As you scroll deeper in the ocean and interact with the fishes you'll learn more about them and the current issues they are facing today.
            </p>
          </div>
          <div className={styles.section}>
            <h2>Aquarium</h2>
            <Image src={"/icons/aquarium.svg"} width={50} height={50}></Image>
            <p>
              The fish icon leads you to an <span>aquarium</span>. Where you can put injured creatures that you rescued into it. You can take care of the fishes until they finally recover and return back to the ocean.
            </p>
          </div>
          <div className={styles.section}>
            <h2>Market</h2>
            <Image src={"/icons/market.svg"} width={50} height={50}></Image>
            <p>This market icon leads you to the shop where you can purchase items for your <span>aquarium</span> and your <span>fishes.</span></p>
          </div>
          <div className={styles.section}>
            <h2>Quiz</h2>
            <Image src={"/icons/quiz.svg"} width={50} height={50}></Image>
            <p>
              Lastly theres a quiz section where you can put your <span>ocean knowledge</span>to the test, you can also earn seashells to purchase items for your aquarium to give your fishes a happy home.
            </p>
          </div>
          <div className={styles.section}>
            <h2>Menu</h2>
            <Image src={"/icons/menu.svg"} width={50} height={50}></Image>
            <p>This icon is the menu, in here you can access the save, settings and quit buttons</p>
          </div>
        </div>
        <div id={"learn"}>

        </div>
      <Navbar></Navbar>
      </main>
    </>
  )
}